services:
  mongodb:
    hostname: mongodb
    container_name: mongodb-container
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27019:27017
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-container
    environment:
      - NODE_ENV=production
      - PORT=1210
      - MONGODB_URI=mongodb://user:pass@mongodb:27017/database?authSource=admin
    ports:
      - 1210:1210
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  frontend-admin:
    build:
      context: ../frontend-admin
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: frontend-admin-container
    ports:
      - 1208:80
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  frontend-client:
    build:
      context: ../frontend-client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: frontend-client-container
    ports:
      - 1209:80
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  data:
  config:

networks:
  app-network:
    driver: bridge
